import { NextRequest, NextResponse } from "next/server";
import dns from "node:dns/promises";

export const runtime = "nodejs";

const MAX_PDF_BYTES = 25 * 1024 * 1024; // 25 MB
const FETCH_TIMEOUT_MS = 15000;

function sanitizeFilename(name: string | null): string {
  const fallback = "resume.pdf";
  if (!name) return fallback;
  const cleaned = name.replace(/[^a-zA-Z0-9 ._-]/g, "").trim();
  if (!cleaned) return fallback;
  return cleaned.toLowerCase().endsWith(".pdf") ? cleaned : `${cleaned}.pdf`;
}

// Blocks loopback/private/link-local ranges (including the 169.254.169.254
// cloud-metadata address) so this proxy can't be used to reach internal
// infrastructure via an attacker-supplied `url` query param.
function isPrivateOrReservedIp(ip: string): boolean {
  if (ip.includes(".")) {
    const parts = ip.split(".").map(Number);
    if (parts.length !== 4 || parts.some((p) => Number.isNaN(p))) return true;
    const [a, b] = parts;
    if (a === 10 || a === 127 || a === 0) return true;
    if (a === 169 && b === 254) return true;
    if (a === 172 && b >= 16 && b <= 31) return true;
    if (a === 192 && b === 168) return true;
    if (a === 100 && b >= 64 && b <= 127) return true; // carrier-grade NAT
    return false;
  }

  const lower = ip.toLowerCase();
  if (lower === "::1") return true;
  if (/^fe[89ab]/.test(lower)) return true; // link-local fe80::/10
  if (lower.startsWith("fc") || lower.startsWith("fd")) return true; // unique local fc00::/7
  if (lower.startsWith("::ffff:")) {
    return isPrivateOrReservedIp(lower.slice("::ffff:".length));
  }
  return false;
}

async function assertPublicHttpsUrl(rawUrl: string): Promise<URL> {
  const parsed = new URL(rawUrl);
  if (parsed.protocol !== "https:") {
    throw new Error("Only https URLs are allowed");
  }
  const { address } = await dns.lookup(parsed.hostname);
  if (isPrivateOrReservedIp(address)) {
    throw new Error("URL resolves to a disallowed host");
  }
  return parsed;
}

/**
 * Proxy-downloads a PDF already generated by the external PDF-generation
 * service (see `generatePdfFromHtml` in profiles/actions.ts). That service
 * returns a hosted URL used for <iframe> preview; browsers ignore the
 * `download` attribute on cross-origin links, so linking to that URL
 * directly doesn't force a save. Routing the download through here instead
 * guarantees a real attachment download regardless of the upstream host.
 */
export async function GET(request: NextRequest): Promise<NextResponse> {
  const rawUrl = request.nextUrl.searchParams.get("url");
  const filename = request.nextUrl.searchParams.get("filename");

  if (!rawUrl) {
    return NextResponse.json({ error: "url is required" }, { status: 400 });
  }

  let target: URL;
  try {
    target = await assertPublicHttpsUrl(rawUrl);
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Invalid url" },
      { status: 400 }
    );
  }

  let upstream: Response;
  try {
    upstream = await fetch(target, {
      redirect: "manual",
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
  } catch {
    return NextResponse.json({ error: "Failed to reach PDF source" }, { status: 502 });
  }

  if (upstream.status >= 300 && upstream.status < 400) {
    return NextResponse.json({ error: "PDF source returned a redirect" }, { status: 502 });
  }

  if (!upstream.ok) {
    return NextResponse.json({ error: "Failed to fetch PDF" }, { status: 502 });
  }

  const contentType = upstream.headers.get("content-type") ?? "";
  if (contentType && !contentType.toLowerCase().includes("pdf")) {
    return NextResponse.json({ error: "Upstream did not return a PDF" }, { status: 415 });
  }

  const contentLength = Number(upstream.headers.get("content-length") ?? "0");
  if (contentLength > MAX_PDF_BYTES) {
    return NextResponse.json({ error: "PDF is too large" }, { status: 413 });
  }

  const buffer = Buffer.from(await upstream.arrayBuffer());
  if (buffer.byteLength > MAX_PDF_BYTES) {
    return NextResponse.json({ error: "PDF is too large" }, { status: 413 });
  }

  return new NextResponse(buffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${sanitizeFilename(filename)}"`,
    },
  });
}
