/**
 * Prime Design System
 *
 * Single entry point for the entire design system.
 *
 * Import paths:
 *   import { Button } from '@/design-system'                        // any named export
 *   import { Button } from '@/design-system/primitives/button'      // per-component (preferred for tree-shaking)
 *   import { colorTokens } from '@/design-system/foundations/tokens'
 */

// ── Foundations ────────────────────────────────────────────────────────────
export * from './foundations/tokens'
export * from './foundations/typography'

// ── Primitives (shadcn/ui vendor zone — do not import from components/ui directly) ──
export * from './primitives/accordion'
export * from './primitives/alert'
export * from './primitives/avatar'
export * from './primitives/badge'
export * from './primitives/button'
export * from './primitives/button-group'
export * from './primitives/card'
export * from './primitives/carousel'
export * from './primitives/collapsible'
export * from './primitives/command'
export * from './primitives/dialog'
export * from './primitives/dropdown-menu'
export * from './primitives/field'
export * from './primitives/hover-card'
export * from './primitives/input'
export * from './primitives/input-group'
export * from './primitives/label'
export * from './primitives/popover'
export * from './primitives/progress'
export * from './primitives/scroll-area'
export * from './primitives/select'
export * from './primitives/separator'
export * from './primitives/sheet'
export * from './primitives/spinner'
export * from './primitives/switch'
export * from './primitives/tabs'
export * from './primitives/textarea'
export * from './primitives/tooltip'

// ── Patterns (app-specific composed components) ────────────────────────────
export * from './patterns/chat'
export * from './patterns/chip-input'
export * from './patterns/dynamic-list'
export * from './patterns/education-builder'
export * from './patterns/experience-builder'
export * from './patterns/file-upload'
export * from './patterns/form-submit-button'
export * from './patterns/job-description-field'
export * from './patterns/list'
export * from './patterns/project-builder'
export * from './patterns/rich-text-editor'
export * from './patterns/skill-builder'
export * from './patterns/social-links-builder'
export * from './patterns/step-nav'

// ── AI Components ──────────────────────────────────────────────────────────
export * from './ai/agent'
export * from './ai/artifact'
export * from './ai/attachments'
export * from './ai/audio-player'
export * from './ai/canvas'
export * from './ai/chain-of-thought'
export * from './ai/checkpoint'
export * from './ai/code-block'
export * from './ai/commit'
export * from './ai/confirmation'
export * from './ai/connection'
export * from './ai/context'
export * from './ai/controls'
export * from './ai/conversation'
export * from './ai/edge'
export * from './ai/environment-variables'
export * from './ai/file-tree'
export * from './ai/floating-create-interview'
export * from './ai/image'
export * from './ai/inline-citation'
export * from './ai/jsx-preview'
export * from './ai/message'
export * from './ai/mic-selector'
export * from './ai/model-selector'
export * from './ai/node'
export * from './ai/open-in-chat'
export * from './ai/package-info'
export * from './ai/panel'
export * from './ai/persona'
export * from './ai/plan'
export * from './ai/prompt-input'
export * from './ai/queue'
export * from './ai/reasoning'
export * from './ai/sandbox'
export * from './ai/schema-display'
export * from './ai/shimmer'
export * from './ai/snippet'
export * from './ai/sources'
export * from './ai/speech-input'
export * from './ai/stack-trace'
export * from './ai/suggestion'
export * from './ai/task'
export * from './ai/terminal'
export * from './ai/test-results'
export * from './ai/tool'
export * from './ai/toolbar'
export * from './ai/transcription'
export * from './ai/voice-selector'
export * from './ai/web-preview'

// ── Layout ─────────────────────────────────────────────────────────────────
export * from './layout/app-shell'
export * from './layout/side-bar'
// Note: layout/panel re-exports the same panel as ai/panel — import from ai/panel directly if needed
